version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    links:
      - mysql
    networks:
      - app-network
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./dockerconfig/nginx/:/etc/nginx/conf.d/
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: testeclicmed
      MYSQL_ROOT_PASSWORD: qwe123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
